require('basics')
require('lsp')
require('plugins')
require('keybindings')
require('telescope-config')
require('cmp-config')
require('nvim-tree-config')
require('nvim-treesitter-config')
require('surround-config')
require('gitsigns-config')
require('discord-presence')
require('zen-mode-config')
require('lualine-config')
require('noice-config')
require('colorscheme-config')
-- require('tabline-config')
-- require('nvim-notify-config')
