require('basics')
require('lsp')
require('plugins')
require('keybindings')
require('telescope-config')
require('cmp-config')
require('nvim-tree-config')
require('nvim-treesitter-config')
require('surround-config')
-- require('null-ls-config')
-- require('discord-presence')
-- require('prettier-config')
-- require('coc-config')
