require('basics')
require('telescope-config')
require('discord-presence')
require('keybindings')
require('lsp')
require('plugins')
require('nvim-tree-config')
require('nvim-treesitter-config')
-- require('null-ls-config')
require('prettier-config')
require('coc-config')
